// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/book/[id].tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/CoverUpload.tsx";
import * as $$1 from "./islands/TopBar.tsx";
import * as $$2 from "./islands/book/Book.tsx";
import * as $$3 from "./islands/book/BookCard.tsx";
import * as $$4 from "./islands/book/BookCover.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/book/[id].tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/CoverUpload.tsx": $$0,
    "./islands/TopBar.tsx": $$1,
    "./islands/book/Book.tsx": $$2,
    "./islands/book/BookCard.tsx": $$3,
    "./islands/book/BookCover.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
