# fly.toml app configuration file generated for wuxia2kindle on 2024-02-16T21:26:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wuxia2kindle'
primary_region = 'ams'

[build]

[env]
  API_URL = "https://wuxia2kindle.arino.io"
  DOMAIN = "wuxia2kindle.arino.io"
  SMTP_SERVER = "smtp.sendgrid.net"
  SMTP_PORT = "587"
  SMTP_USER = "apikey"
  SEND_TO = "arinono@kindle.com"
  FROM = "kindle@arino.io"
  DISCORD_REDIRECT_URI = "https://wuxia2kindle.arino.io/auth/discord/callback"
  WORKER_URL = "http://worker.process.wuxia2kindle.internal:3001"

[processes]
  server = '/app/bin server'
  worker = '/app/bin worker'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['server']

[[http_service.checks]]
  grace_period = "5s"
  interval = "5s"
  method = "GET"
  timeout = "5s"
  path = "/health"
  process = ["server"]

[[vm]]
  size = 'shared-cpu-1x'
