[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", features = ["macros"] }
clap = { version = "4.3.11", features = ["derive"] }
serde = { version = "1.0.170", features = ["derive"] }
serde_json = "1.0.100"
sqlx = { version = "0.7.0", features = ["postgres", "runtime-tokio-rustls"] }
tokio = { version = "1.29.1", features = ["full"] }
