# fly.toml app configuration file generated for wuxia2kindle-minio on 2024-02-24T17:24:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wuxia2kindle-minio'
primary_region = 'ams'

[build]

[mounts]
source = "miniodata"
destination = "/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
